[package]
name = "utils"
edition.workspace = true
version.workspace = true

[features]
default = []

jsonwebtoken = ["dep:jiff", "dep:jsonwebtoken", "dep:serde"]
lettre = ["dep:lettre", "dep:tokio"]
maxminddb = [
	"dep:flate2",
	"dep:ip-discovery",
	"dep:jiff",
	"dep:maxminddb",
	"dep:reqwest",
	"dep:tar",
	"dep:tokio",
]
maxminddb-axum = ["maxminddb", "dep:axum", "dep:itertools"]

[dependencies]
axum = { workspace = true, optional = true }
itertools = { workspace = true, optional = true }
jiff = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true }
tracing = { workspace = true }

flate2 = { version = "1.1.10", optional = true }
ip-discovery = { version = "0.5.1", optional = true, features = ["async"] }
jsonwebtoken = { version = "11.1.0", optional = true }
lettre = { version = "0.11.23", optional = true, default-features = false, features = [
	"builder",
	"hostname",
	"pool",
	"smtp-transport",
	"tokio1-rustls",
	"aws-lc-rs",
	"webpki-roots",
] }
maxminddb = { version = "0.32.0", optional = true }
tar = { version = "0.4.46", optional = true }
