[package]
name = "utils"
edition.workspace = true
version.workspace = true

[features]
default = []

jsonwebtoken = ["dep:chrono", "dep:jsonwebtoken", "dep:serde"]
lettre = ["dep:lettre", "dep:tokio"]
maxminddb = [
  "dep:chrono",
  "dep:chrono-tz",
  "dep:flate2",
  "dep:ip-discovery",
  "dep:maxminddb",
  "dep:reqwest",
  "dep:tar",
  "dep:tokio",
]
maxminddb-axum = ["maxminddb", "dep:axum"]

[dependencies]
axum = { workspace = true, optional = true }
chrono = { workspace = true, optional = true }
chrono-tz = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true }
tracing = { workspace = true }

flate2 = { version = "1.1.10", optional = true }
ip-discovery = { version = "0.5.0", optional = true, features = ["async"] }
jsonwebtoken = { version = "11.0.0", optional = true }
lettre = { version = "0.11.23", optional = true, features = [
  "tokio1",
  "tokio1-native-tls",
] }
maxminddb = { version = "0.30.3", optional = true }
tar = { version = "0.4.46", optional = true }
