[workspace]
members = [
  # apps
  "app/template_readonly",
  # "app/image",
  # libs
  "libs/identifiers",
  "libs/telemetry",
  "libs/utils",
]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.1.1"

[workspace.dependencies]
anyhow = "1.0.104"
axum = { version = "0.8.9", features = ["macros"] }
axum-extra = { version = "0.12.6", features = ["form"] }
chrono = { version = "0.4.45", default-features = false, features = [
  "clock",
  "serde",
] }
chrono-tz = { version = "0.10.4" }
dotenvy = "0.15.7"
futures = "0.3.34"
hitbox = { version = "0.2.4", features = ["metrics"] }
hitbox-backend = "0.2.1"
hitbox-fn = { version = "0.2.1", features = ["derive"] }
hitbox-http = "0.2.1"
hitbox-moka = "0.2.0"
hitbox-redis = "0.2.1"
hitbox-reqwest = "0.2.0"
hitbox-tower = "0.2.0"
hypertext = { version = "0.12.1", features = ["axum"] }
num-traits = "0.2.19"
rand = "0.10.2"
reqwest = { version = "0.13.4", default-features = false, features = [
  "native-tls",
  "json",
] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["preserve_order"] }
sqlx = { version = "0.9.0", default-features = false, features = [
  "postgres",
  "runtime-tokio",
  "tls-native-tls",
  "macros",
  "migrate",
  "bigdecimal",
  "chrono",
  "ipnetwork",
  "json",
  "uuid",
] }
thiserror = { version = "2.0.18" }
tokio = { version = "1.53.1", features = ["full"] }
tower = { version = "0.5.3", features = ["timeout", "util"] }
tower-http = { version = "0.7.0", features = [
  "trace",
  "fs",
  "timeout",
  "compression-full",
] }
tower_governor = { version = "0.8.0" }
tracing = "0.1.44"
url = "2.5.8"

identifiers = { path = "libs/identifiers" }
telemetry = { path = "libs/telemetry" }
utils = { path = "libs/utils" }
